DATABRICKS_HTTP_PATH="/sql/1.0/warehouses/148ccb90800933a1"
DATABRICKS_SERVER_HOSTNAME="adb-984752964297111.11.azuredatabricks.net"
DATABRICKS_CLIENT_ID="2130e00f-683f-4a58-8a2a-f992d143079a"
DATABRICKS_CLIENT_SECRET="dosed83121292c6f3994e307546552017030"